### ISSUE TITLE
Support for SNAPSHOT releases

### ISSUE THREAD

**Issue by Turbo87** [Zoltu/Gradle.Plugin.Versioning#16]
I've been using a similar approach to this plugin in my Gradle scripts with one small difference. Instead of appending `-{count}` to the version number I appended `-SNAPSHOT` (unless it's a tagged commit), and in the publish script I check for that suffix to determine in which Maven repository the jar files should be published.

Do you think something like that makes sense? Is this something that could be supported by the plugin?

**Comment by MicahZoltu** [comment]
@Turbo87 My intention is for this plugin to be a continuous deployment (CD) versioning system, which means there is no such thing as a "SNAPSHOT" build in that every build is publishable with a well defined version number.

However, you could get the `-SNAPSHOT` version number by applying a tag like `v1.2-SNAPSHOT` and then your versions would look like `1.2.{count}-SNAPSHOT`.  This would require that you tag twice for every version, one with the version you want (e.g., `v1.2`) and another on the following commit with the snapshot tag (e.g., `v1.3-SNAPSHOT`), so not an ideal solution for your situation.

Another option would be for me to expose the [`VersionInfo`](https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/main/kotlin/com/zoltu/gradle/plugin/VersionInfo.kt#L4-L9) object to the user's gradle script.  Then you could do something like the following in your `build.gradle`.

``` groovy
if (ext.versionInfo.count == 0) {
    version = "${versionInfo.major}.${versionInfo.minor}"
    // TODO set publish destination to release destination
} else {
    version = "${versionInfo.major}.${versionInfo.minor}-SNAPSHOT"
    // TODO set publish destination to snapshot destination
}
```

The above could be achieved right now by running the current `version` attribute through a regex, but that would get somewhat ugly in your `build.gradle`.

Let me know if you think exposing the `VersionInfo` object would be valuable to you and I'll make that change.

**Comment by Turbo87** [comment]
I was actually thinking about a simple config option like this 

``` groovy
gitVersion {
  useSnapshots = true
}
```

but then I remembered one of my Android projects where I'm doing this:

``` groovy
def versionMajor = 1
def versionMinor = 2
def versionPatch = 0

android {
    defaultConfig {
        versionCode versionMajor * 10000 + versionMinor * 100 + versionPatch
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"
    }
}
```

I guess if you exposed the `versionInfo` like suggested above we could start using this plugin for Android builds too.

**Comment by MicahZoltu** [comment]
I submitted a [forum inquiry](https://discuss.gradle.org/t/how-do-i-expose-a-variable-from-a-plugin-to-the-project/19129) asking for details on what the best/most correct way for a plugin to expose a variable like this is.  I'm going to let that bake for a day or two but if I don't get an answer I'll just go with the `project.ext` solution.  I'll update this issue once a new version is released that exposes the `versionInfo` object to plugin users, then you should be able to do:

```
plugins { id "com.zoltu.git-versioning" version "2.0.x" }

def versionMajor = something.versionInfo.major
def versionMinor = something.versionInfo.minor
def versionPatch = something.versionInfo.commitCount
...
```

**Comment by Turbo87** [comment]
Awesome, thanks!

**Comment by MicahZoltu** [comment]
Sample Usage:

``` groovy
def versionInfo = ZoltuGitVersioning.versionInfo
print "${versionInfo.major}.${versionInfo.minor}.${versionInfo.commitCount}"
```

**Comment by Turbo87** [comment]
Cool. I'll try that out.

**Comment by MicahZoltu** [comment]
The latest version (major version bump to v3.x) removes semantic versioning out-of-the-box in favor of allowing users to fully customize the way version info is extracted.  Out-of-the-box now only supports versioning like `v1.2` with optional tags.

If you find that the latest version breaks your workflow in some way (I'm not sure how exactly you ended up using the plugin) then you can add a custom describe processor to make the plugin do whatever you want in terms of how the git describe results are parsed and how you format the final output version string.  Details can be found in the readme, or you can see an example `build.gradle` file in the tests; the same tests passed before without a custom describe processor, so the regex in these tests should match the previous semantic versioning scheme, allowing you to easily copy/paste the block into your `build.gradle` without any changes.
https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/test/kotlin/FunctionalTests.kt#L107-L112
https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/test/kotlin/FunctionalTests.kt#L87-L92

**Comment by Turbo87** [comment]
@MicahZoltu thanks for the update, I'll have a look!
