### ISSUE TITLE
seems to Jar is correctly hooked, but distribution isn't

### ISSUE THREAD

**Issue by childnode** [Zoltu/Gradle.Plugin.Versioning#6]
when creating tarballs or zips with the [distribution plugin](https://docs.gradle.org/current/userguide/distribution_plugin.html) / with [application](https://docs.gradle.org/current/userguide/application_plugin.html), the MANIFEST is missing since the plugin generates it in build/tmp and adds it to the jar but distribution (and I bet also others) doesn't know about the `build/tmp`, so I suggest to generate the manifest into the `build/resources`

**Comment by MicahZoltu** [comment]
I'll look into this tomorrow.  The setting of version in the manifest is done via the jar task closure that comes with gradle.  In theory, it should be the same as setting the manifest attributes directly in your `build.gradle` with something like

``` groovy
jar {
    manifest {
        ...
    }
}
```

If you have repro steps let me know.  If not I'll try to repro tomorrow with `installDist`.

**Comment by childnode** [comment]
mhh ... ok, had a [quick peek in the code](https://github.com/Zoltu/Gradle.Plugin.Versioning/blob/master/src/main/kotlin/com/zoltu/gradle/plugin/GitVersioning.kt#L18) so Jar.manifest is used to set this... so if distribution not uses the manifest, it either doesn't use the Jar ... http://stackoverflow.com/questions/35766184
<< not a Gradle.Plugin.Versioning bug

P.S: thx @Zoltu

**Comment by MicahZoltu** [comment]
Closing this issue since it sounds like the problem you are having is not with this plugin.  When I tested this, I saw the manifest in the JAR after doing `installDist`.

Feel free to re-open or ping if you still believe this is an issue with this plugin!

**Comment by childnode** [comment]
@Zoltu : yes, you're right, it's neither a gradle, nor a Versioning plugin bug, it's caused on my side by the ratpack gradle plugin ... jfyi: https://gist.github.com/childnode/d96c084ac088d2d94b44
I'm sorry
